// <auto-generated />
using Fruitway_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fruitway_Store.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    partial class ApplicationDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fruitway_Store.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrandingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
                            ImageUrl = "",
                            IsTrandingProduct = true,
                            Name = "Lemon",
                            Price = 85m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
                            ImageUrl = "",
                            IsTrandingProduct = true,
                            Name = "Berry",
                            Price = 70m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
                            ImageUrl = "",
                            IsTrandingProduct = true,
                            Name = "Strawberry",
                            Price = 45m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
                            ImageUrl = "",
                            IsTrandingProduct = true,
                            Name = "Strawberry",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
                            ImageUrl = "",
                            IsTrandingProduct = true,
                            Name = "Green Apple",
                            Price = 60m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
                            ImageUrl = "",
                            IsTrandingProduct = true,
                            Name = "Avocado",
                            Price = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
